services:
  db:
    image: postgres:16
    container_name: surveygate_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: surveygate_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: