"""schema v2 surveys segments invitations

Revision ID: e62d283761b7
Revises: 5542f800f6ee
Create Date: 2026-02-11 12:32:25.834366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e62d283761b7'
down_revision: Union[str, Sequence[str], None] = '5542f800f6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft','active','closed')", name='ck_surveys_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_surveys_status', 'surveys', ['status'], unique=False)
    op.create_table('survey_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('message_template', sa.String(), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_sends_segment_id', 'survey_sends', ['segment_id'], unique=False)
    op.create_index('ix_survey_sends_survey_id', 'survey_sends', ['survey_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('send_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['send_id'], ['survey_sends.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invitations_expires_at', 'invitations', ['expires_at'], unique=False)
    op.create_index('ix_invitations_survey_id_user_id', 'invitations', ['survey_id', 'user_id'], unique=False)
    op.create_index('uq_invitations_active_survey_user', 'invitations', ['survey_id', 'user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL AND used_at IS NULL'))
    op.create_index('uq_invitations_token_hash', 'invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_invitations_token_hash', table_name='invitations')
    op.drop_index('uq_invitations_active_survey_user', table_name='invitations', postgresql_where=sa.text('revoked_at IS NULL AND used_at IS NULL'))
    op.drop_index('ix_invitations_survey_id_user_id', table_name='invitations')
    op.drop_index('ix_invitations_expires_at', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_survey_sends_survey_id', table_name='survey_sends')
    op.drop_index('ix_survey_sends_segment_id', table_name='survey_sends')
    op.drop_table('survey_sends')
    op.drop_index('ix_surveys_status', table_name='surveys')
    op.drop_table('surveys')
    op.drop_table('segments')
    # ### end Alembic commands ###
