"""schema v1 users catalogs m2m

Revision ID: 5542f800f6ee
Revises:
Create Date: 2026-02-06 11:42:03.117446

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5542f800f6ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_code"), "devices", ["code"], unique=True)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_code"), "services", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("has_children", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_age", "users", ["age"], unique=False)
    op.create_index("ix_users_city", "users", ["city"], unique=False)
    op.create_table(
        "user_devices",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "device_id"),
    )
    op.create_index("ix_user_devices_device_id", "user_devices", ["device_id"], unique=False)
    op.create_index("ix_user_devices_user_id", "user_devices", ["user_id"], unique=False)
    op.create_table(
        "user_identities",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("telegram_id", name="uq_user_identities_telegram_id"),
    )
    op.create_index(
        "ix_user_identities_telegram_id", "user_identities", ["telegram_id"], unique=False
    )
    op.create_table(
        "user_services",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "service_id"),
    )
    op.create_index("ix_user_services_service_id", "user_services", ["service_id"], unique=False)
    op.create_index("ix_user_services_user_id", "user_services", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_services_user_id", table_name="user_services")
    op.drop_index("ix_user_services_service_id", table_name="user_services")
    op.drop_table("user_services")
    op.drop_index("ix_user_identities_telegram_id", table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index("ix_user_devices_user_id", table_name="user_devices")
    op.drop_index("ix_user_devices_device_id", table_name="user_devices")
    op.drop_table("user_devices")
    op.drop_index("ix_users_city", table_name="users")
    op.drop_index("ix_users_age", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_services_code"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_devices_code"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
